/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloudhub.client.JSON;

/**
 * GetServiceAvailabilityResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class GetServiceAvailabilityResponse {
  public static final String SERIALIZED_NAME_DISCOVERY_AVAILABLE = "discoveryAvailable";
  @SerializedName(SERIALIZED_NAME_DISCOVERY_AVAILABLE)
  @javax.annotation.Nullable
  private Boolean discoveryAvailable;

  public static final String SERIALIZED_NAME_CERTIFICATE_FOUND = "certificateFound";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_FOUND)
  @javax.annotation.Nullable
  private Boolean certificateFound;

  public GetServiceAvailabilityResponse() {
  }

  public GetServiceAvailabilityResponse discoveryAvailable(@javax.annotation.Nullable Boolean discoveryAvailable) {
    this.discoveryAvailable = discoveryAvailable;
    return this;
  }

  /**
   * Get discoveryAvailable
   * @return discoveryAvailable
   */
  @javax.annotation.Nullable
  public Boolean getDiscoveryAvailable() {
    return discoveryAvailable;
  }

  public void setDiscoveryAvailable(@javax.annotation.Nullable Boolean discoveryAvailable) {
    this.discoveryAvailable = discoveryAvailable;
  }


  public GetServiceAvailabilityResponse certificateFound(@javax.annotation.Nullable Boolean certificateFound) {
    this.certificateFound = certificateFound;
    return this;
  }

  /**
   * Get certificateFound
   * @return certificateFound
   */
  @javax.annotation.Nullable
  public Boolean getCertificateFound() {
    return certificateFound;
  }

  public void setCertificateFound(@javax.annotation.Nullable Boolean certificateFound) {
    this.certificateFound = certificateFound;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetServiceAvailabilityResponse getServiceAvailabilityResponse = (GetServiceAvailabilityResponse) o;
    return Objects.equals(this.discoveryAvailable, getServiceAvailabilityResponse.discoveryAvailable) &&
        Objects.equals(this.certificateFound, getServiceAvailabilityResponse.certificateFound);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(discoveryAvailable, certificateFound);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetServiceAvailabilityResponse {\n");
    sb.append("    discoveryAvailable: ").append(toIndentedString(discoveryAvailable)).append("\n");
    sb.append("    certificateFound: ").append(toIndentedString(certificateFound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("discoveryAvailable", "certificateFound"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetServiceAvailabilityResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetServiceAvailabilityResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetServiceAvailabilityResponse is not found in the empty JSON string", GetServiceAvailabilityResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetServiceAvailabilityResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetServiceAvailabilityResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetServiceAvailabilityResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetServiceAvailabilityResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetServiceAvailabilityResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetServiceAvailabilityResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetServiceAvailabilityResponse>() {
           @Override
           public void write(JsonWriter out, GetServiceAvailabilityResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetServiceAvailabilityResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetServiceAvailabilityResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetServiceAvailabilityResponse
   * @throws IOException if the JSON string is invalid with respect to GetServiceAvailabilityResponse
   */
  public static GetServiceAvailabilityResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetServiceAvailabilityResponse.class);
  }

  /**
   * Convert an instance of GetServiceAvailabilityResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

