/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub.client.model;

import java.util.Objects;
import cloudhub.client.model.IdentifierTypes;
import cloudhub.client.model.TrustServiceSessionTypes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloudhub.client.JSON;

/**
 * SessionCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SessionCreateRequest {
  public static final String SERIALIZED_NAME_IDENTIFIER_TYPE = "identifierType";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_TYPE)
  @javax.annotation.Nullable
  private IdentifierTypes identifierType;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  @javax.annotation.Nullable
  private String identifier;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private TrustServiceSessionTypes type;

  public static final String SERIALIZED_NAME_REDIRECT_URI = "redirectUri";
  @SerializedName(SERIALIZED_NAME_REDIRECT_URI)
  @javax.annotation.Nonnull
  private String redirectUri;

  public static final String SERIALIZED_NAME_LIFETIME_IN_SECONDS = "lifetimeInSeconds";
  @SerializedName(SERIALIZED_NAME_LIFETIME_IN_SECONDS)
  @javax.annotation.Nullable
  private Integer lifetimeInSeconds;

  public static final String SERIALIZED_NAME_CUSTOM_STATE = "customState";
  @SerializedName(SERIALIZED_NAME_CUSTOM_STATE)
  @javax.annotation.Nullable
  private String customState;

  public static final String SERIALIZED_NAME_DISCOVER = "discover";
  @SerializedName(SERIALIZED_NAME_DISCOVER)
  @javax.annotation.Nullable
  private Boolean discover;

  public SessionCreateRequest() {
  }

  public SessionCreateRequest identifierType(@javax.annotation.Nullable IdentifierTypes identifierType) {
    this.identifierType = identifierType;
    return this;
  }

  /**
   * Get identifierType
   * @return identifierType
   */
  @javax.annotation.Nullable
  public IdentifierTypes getIdentifierType() {
    return identifierType;
  }

  public void setIdentifierType(@javax.annotation.Nullable IdentifierTypes identifierType) {
    this.identifierType = identifierType;
  }


  public SessionCreateRequest identifier(@javax.annotation.Nullable String identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @javax.annotation.Nullable
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(@javax.annotation.Nullable String identifier) {
    this.identifier = identifier;
  }


  public SessionCreateRequest type(@javax.annotation.Nullable TrustServiceSessionTypes type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public TrustServiceSessionTypes getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable TrustServiceSessionTypes type) {
    this.type = type;
  }


  public SessionCreateRequest redirectUri(@javax.annotation.Nonnull String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * Get redirectUri
   * @return redirectUri
   */
  @javax.annotation.Nonnull
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(@javax.annotation.Nonnull String redirectUri) {
    this.redirectUri = redirectUri;
  }


  public SessionCreateRequest lifetimeInSeconds(@javax.annotation.Nullable Integer lifetimeInSeconds) {
    this.lifetimeInSeconds = lifetimeInSeconds;
    return this;
  }

  /**
   * Get lifetimeInSeconds
   * @return lifetimeInSeconds
   */
  @javax.annotation.Nullable
  public Integer getLifetimeInSeconds() {
    return lifetimeInSeconds;
  }

  public void setLifetimeInSeconds(@javax.annotation.Nullable Integer lifetimeInSeconds) {
    this.lifetimeInSeconds = lifetimeInSeconds;
  }


  public SessionCreateRequest customState(@javax.annotation.Nullable String customState) {
    this.customState = customState;
    return this;
  }

  /**
   * Get customState
   * @return customState
   */
  @javax.annotation.Nullable
  public String getCustomState() {
    return customState;
  }

  public void setCustomState(@javax.annotation.Nullable String customState) {
    this.customState = customState;
  }


  public SessionCreateRequest discover(@javax.annotation.Nullable Boolean discover) {
    this.discover = discover;
    return this;
  }

  /**
   * Get discover
   * @return discover
   */
  @javax.annotation.Nullable
  public Boolean getDiscover() {
    return discover;
  }

  public void setDiscover(@javax.annotation.Nullable Boolean discover) {
    this.discover = discover;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionCreateRequest sessionCreateRequest = (SessionCreateRequest) o;
    return Objects.equals(this.identifierType, sessionCreateRequest.identifierType) &&
        Objects.equals(this.identifier, sessionCreateRequest.identifier) &&
        Objects.equals(this.type, sessionCreateRequest.type) &&
        Objects.equals(this.redirectUri, sessionCreateRequest.redirectUri) &&
        Objects.equals(this.lifetimeInSeconds, sessionCreateRequest.lifetimeInSeconds) &&
        Objects.equals(this.customState, sessionCreateRequest.customState) &&
        Objects.equals(this.discover, sessionCreateRequest.discover);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifierType, identifier, type, redirectUri, lifetimeInSeconds, customState, discover);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionCreateRequest {\n");
    sb.append("    identifierType: ").append(toIndentedString(identifierType)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    lifetimeInSeconds: ").append(toIndentedString(lifetimeInSeconds)).append("\n");
    sb.append("    customState: ").append(toIndentedString(customState)).append("\n");
    sb.append("    discover: ").append(toIndentedString(discover)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("identifierType", "identifier", "type", "redirectUri", "lifetimeInSeconds", "customState", "discover"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("redirectUri"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SessionCreateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SessionCreateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SessionCreateRequest is not found in the empty JSON string", SessionCreateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SessionCreateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SessionCreateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SessionCreateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `identifierType`
      if (jsonObj.get("identifierType") != null && !jsonObj.get("identifierType").isJsonNull()) {
        IdentifierTypes.validateJsonElement(jsonObj.get("identifierType"));
      }
      if ((jsonObj.get("identifier") != null && !jsonObj.get("identifier").isJsonNull()) && !jsonObj.get("identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identifier").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TrustServiceSessionTypes.validateJsonElement(jsonObj.get("type"));
      }
      if (!jsonObj.get("redirectUri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `redirectUri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("redirectUri").toString()));
      }
      if ((jsonObj.get("customState") != null && !jsonObj.get("customState").isJsonNull()) && !jsonObj.get("customState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customState").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SessionCreateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SessionCreateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SessionCreateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SessionCreateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SessionCreateRequest>() {
           @Override
           public void write(JsonWriter out, SessionCreateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SessionCreateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SessionCreateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SessionCreateRequest
   * @throws IOException if the JSON string is invalid with respect to SessionCreateRequest
   */
  public static SessionCreateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SessionCreateRequest.class);
  }

  /**
   * Convert an instance of SessionCreateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

