/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TrustServiceSessionTypes
 */
@JsonAdapter(TrustServiceSessionTypes.Adapter.class)
public enum TrustServiceSessionTypes {
  
  NUMBER_1(1),
  
  NUMBER_2(2),
  
  NUMBER_3(3),
  
  NUMBER_4(4);

  private Integer value;

  TrustServiceSessionTypes(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TrustServiceSessionTypes fromValue(Integer value) {
    for (TrustServiceSessionTypes b : TrustServiceSessionTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TrustServiceSessionTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final TrustServiceSessionTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TrustServiceSessionTypes read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return TrustServiceSessionTypes.fromValue(value);
    }
  }
}

