/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub.client.model;

import cloudhub.client.model.TrustServiceSessionTypes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceSessionCreateRequest
 */
public class ServiceSessionCreateRequestTest {
    private final ServiceSessionCreateRequest model = new ServiceSessionCreateRequest();

    /**
     * Model tests for ServiceSessionCreateRequest
     */
    @Test
    public void testServiceSessionCreateRequest() {
        // TODO: test ServiceSessionCreateRequest
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'redirectUri'
     */
    @Test
    public void redirectUriTest() {
        // TODO: test redirectUri
    }

    /**
     * Test the property 'lifetimeInSeconds'
     */
    @Test
    public void lifetimeInSecondsTest() {
        // TODO: test lifetimeInSeconds
    }

}
