/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SignHashRequest
 */
public class SignHashRequestTest {
    private final SignHashRequest model = new SignHashRequest();

    /**
     * Model tests for SignHashRequest
     */
    @Test
    public void testSignHashRequest() {
        // TODO: test SignHashRequest
    }

    /**
     * Test the property 'session'
     */
    @Test
    public void sessionTest() {
        // TODO: test session
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'digestAlgorithm'
     */
    @Test
    public void digestAlgorithmTest() {
        // TODO: test digestAlgorithm
    }

    /**
     * Test the property 'digestAlgorithmOid'
     */
    @Test
    public void digestAlgorithmOidTest() {
        // TODO: test digestAlgorithmOid
    }

    /**
     * Test the property 'certificateAlias'
     */
    @Test
    public void certificateAliasTest() {
        // TODO: test certificateAlias
    }

}
