/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub.client.model;

import cloudhub.client.model.TrustServiceInfoModel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TrustServiceAuthParametersModel
 */
public class TrustServiceAuthParametersModelTest {
    private final TrustServiceAuthParametersModel model = new TrustServiceAuthParametersModel();

    /**
     * Model tests for TrustServiceAuthParametersModel
     */
    @Test
    public void testTrustServiceAuthParametersModel() {
        // TODO: test TrustServiceAuthParametersModel
    }

    /**
     * Test the property 'serviceInfo'
     */
    @Test
    public void serviceInfoTest() {
        // TODO: test serviceInfo
    }

    /**
     * Test the property 'authUrl'
     */
    @Test
    public void authUrlTest() {
        // TODO: test authUrl
    }

}
