/*
 * Cloudhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudhub;

import cloudhub.client.ApiException;
import cloudhub.client.Configuration;
import cloudhub.client.model.SessionCreateRequest;
import cloudhub.client.model.SessionModel;
import cloudhub.client.model.SignHashRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SessionsApi
 */
@Disabled
public class SessionsApiTest {

    private final SessionsApi api = new SessionsApi(Configuration.getDefaultCloudhubClient());

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiSessionsCertificateGetTest() throws ApiException {
        String session = null;
        byte[] response = api.apiSessionsCertificateGet(session);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiSessionsPostTest() throws ApiException {
        SessionCreateRequest sessionCreateRequest = null;
        SessionModel response = api.apiSessionsPost(sessionCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiSessionsSignHashPostTest() throws ApiException {
        SignHashRequest signHashRequest = null;
        byte[] response = api.apiSessionsSignHashPost(signHashRequest);
        // TODO: test validations
    }

}
